apiVersion: v1
kind: Service
metadata:
  name: catalogue-cassandra
  namespace: checkplace
spec:
  selector:
    app: checkplace
    service: catalogue-cassandra
  ports:
  - name: cql
    protocol: TCP
    port: 9042
