apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkplace-fe-deployment
  labels:
    app: checkplace
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
      app: checkplace
  template:
    metadata:
      labels:
        tier: frontend
        app: checkplace
    spec:
      containers:
        - name: checkplace-fe-pod
          image: sebastianrevuelta/checkplace-fe:3.6
          imagePullPolicy: Always
          env:
            - name: BACKEND_HOST
              value: checkplace-be-service
            - name: BACKEND_PORT
              value: "8099"
          ports:
            - containerPort: 80
