apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkplace-be-pod
  namespace: checkplace
  labels:
    app: checkplace
    name: checkplace-be-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: checkplace-be-pod
  template:
    metadata:
      labels:
        name: checkplace-be-pod
    spec:
      initContainers:
      - name: init-check-license-service
        image: sebastianrevuelta/check-license:0.0.13
      containers:
        - name: checkplace-be-pod
          image: sebastianrevuelta/checkplace-be:3.1
          imagePullPolicy: Always
          env:
            - name: JAVA_TOOL_OPTIONS
              value: -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
            - name: MARIADB_HOST
              value: "mariadb-service"
            - name: MARIADB_PORT
              value: "3306"
            - name: MARIADB_USER
              value: "root"
            - name: MARIADB_PASS
              value: "capablanca"
          ports:
            - containerPort: 8099
          #securityContext:
          #  runAsUser: 1000
          #  runAsGroup: 3000

