apiVersion: v1
kind: Pod
metadata:
  name: checkplace-fe-pod
  labels:
    name: checkplace-fe
    app: checkplace
spec:
    containers:
      - name: checkplace-fe
        image: sebastianrevuelta/checkplace-fe:3.6
        imagePullPolicy: Always
        env:
          - name: BACKEND_HOST
            value: checkplace-be-service
          - name: BACKEND_PORT
            value: "8099"
        ports:
          - containerPort: 80
