apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkplace-fe-pod
  namespace: checkplace
  labels:
    name: checkplace-fe-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: checkplace-fe-pod
  template:
    metadata:
      labels:
        name: checkplace-fe-pod
    spec:
      containers:
        - name: checkplace-fe-pod
          image: sebastianrevuelta/checkplace-fe:3.6
          imagePullPolicy: Always
          ports:
            - containerPort: 80
