apiVersion: v1
kind: Service
metadata: 
  name: checkplace-fe-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007
  selector:
    tier: frontend
    app: checkplace