apiVersion: v1
kind: Service
metadata:
  name: mariadb
spec:
  type: NodePort
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
      nodePort: 30006
  selector:
    name: mariadb-pod
    app: checkplace