apiVersion: apps/v1
kind: Deployment
metadata:
  name: mariadb-pod
  namespace: checkplace
  labels:
    name: mariadb-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: mariadb-pod
  template:
    metadata:
      name: mariadb-pod
      labels:
        name: mariadb-pod
    spec:
      containers:
        - image: sebastianrevuelta/mariadb:10.6.1
          name: mariadb
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "capablanca"
            - name: MYSQL_DATABASE
              value: "checkplace"
            - name:  MYSQL_USER
              value: "carlsen"
            - name: MYSQL_PASSWORD
              value: "carlsen"
          ports:
            - containerPort: 3306
          resources: {}
      dnsPolicy: ClusterFirst
      restartPolicy: Always
status: {}