apiVersion: v1
kind: Pod

metadata:
  name: mariadb-pod
  labels:
    name: mariadb-pod
    app: checkplace
spec:
  containers:
    - image: sebastianrevuelta/mariadb:10.6.1
      name: mariadb
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: "capablanca"
        - name: MYSQL_DATABASE
          value: "checkplace"
        - name:  MYSQL_USER
          value: "carlsen"
        - name: MYSQL_PASSWORD
          value: "carlsen"
      ports:
        - containerPort: 3306
      resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}