apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: default-deny-ingress
spec:
  podSelector: {}
  policyTypes:
  - Ingress
#apiVersion: "cilium.io/v2"
#kind: CiliumNetworkPolicy
#metadata:
#  name: default-deny-ingress
#specs:
#  - endpointSelector:
#      matchLabels:
#        app: checkplace
#        service: mariadb-service
#    ingress:
#      - fromEndpoints:
#          - matchLabels:
#              app: checkplace
#              service: checkplace-be-service
