version: '3.8'
services:

  checkplace-be:
    image: checkplace-be:1.4
    environment:
      JAVA_TOOL_OPTIONS: -agentlib:jdwp=transport=dt_socket,address=5005,server=y,suspend=n
    container_name: checkplace-be
    ports: 
      - 8099:8080
      - 5005:5005
 
  checkplace-fe:
    image: checkplace-fe:1.4
    container_name: checkplace-fe
    ports: 
      - 4200:80

  mariadb:
     image: mariadb:10.5.8
     container_name: mariadb
     env_file:
       - ./db/mariadb.env
     deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
     ports:
       - "3306:3306"
     command: --innodb-flush-method=fsync
     volumes:
       - ${pwd}/mariadbdata:/var/lib/mysql
       - ./db/schemas.sql:/docker-entrypoint-initdb.d/schemas.sql:ro

